### ISSUE TITLE
No tray icon on Manjaro Gnome

### ISSUE THREAD

**Issue by wmutschl** [flathub/com.mattermost.Desktop#12]
Hi, I am on the latest Manjaro Gnome and installed the Desktop Application; however, when I close it and run it in the background, I would like to have a tray icon to see that Mattermost is still running and if new notifications arrive. Unfortunately, there is no icon. Is this a known issue or did I do something wrong?

**Comment by SemaiCZE** [comment]
Hi, Gnome Shell removed tray icons a while ago, I think since 3.26 or so. If you want some sort of tray icon support, you can try one of the Gnome Shell extensions that bring it back, for example https://extensions.gnome.org/extension/1031/topicons/. Please let me know if it helps. However I'm just a maintainer of the Flathub package, further questions may be better to bring to the developers of this app, here https://github.com/mattermost/desktop. Thanks
