### ISSUE TITLE
Wrong tray notification icon 

### ISSUE THREAD

**Issue by alexbrrsclnt** [flathub/com.mattermost.Desktop#13]
Hi! 

the notificaciont icon that appears in system tray is not correct. It should be the same app icon with a little red circle to show that a new message has been received.

The third icon on the left side:
![mattermost_notification_icon](https://user-images.githubusercontent.com/3874295/83512736-f3e14100-a4d0-11ea-886e-30ebda7e57d0.jpeg)

**Comment by SemaiCZE** [comment]
Hi,
please report the issue to [mattermost/desktop](https://github.com/mattermost/desktop) project. I'm not involved in development, I just take their releases and make flatpak from them. I'm on Gnome, so I have no system tray icons and can't test the bug. You can try to run AppImage version from the releases page (https://releases.mattermost.com/desktop/4.4.2/mattermost-desktop-4.4.2-linux-x86_64.AppImage) and see if the issue is present.
In a case it's related to flatpak version only I can look into it, but I don't think it's the case.

**Comment by fourstepper** [comment]
Could you try with the proposed pull request @alexbrrsclnt ? Thanks

**Comment by SemaiCZE** [comment]
@alexbrrsclnt Is it working for you? If yes please let me know. Thanks

**Comment by alexbrrsclnt** [comment]
Now is working correctly. 👍

**Comment by vchernin** [comment]
@alexbrrsclnt the stable version of the Flatpak should have had the change in #20 [since February](https://github.com/flathub/com.mattermost.Desktop/pull/22). Is this still an issue for you?

**Comment by alexbrrsclnt** [comment]
No, not anymore. Working as expected for months.

Thanks!
